# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/miso_C/test_data_bone.npy
  label_path: ./data/miso_C/test_label.pkl
  debug: False

# model
model: model.msg3d_nia.Model
model_args:
  num_class: 4
  num_point: 18
  num_person: 1
  in_channels: 2
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.kinetics.AdjMatrixGraph


# test
phase: test
device: 0
test_batch_size: 16
weights: ./work_dir/miso_C/bone/weights/weights-32-960.pt

work_dir: ./eval/miso_C/bone/
save_score: True